update function warmup version and schema
* The schema seems to have changed for the serverless.yml
  between version 4.x and 6.x at a minimum
* The 4.x plugin version was compatible with the serverless.yml
  but was using a deprecated 12.x Lambda runtime thus failing
  to deploy
* The 6.x version was getting
  TypeError: Cannot convert undefined or null
* There were serverless dev dependencies that were forcing
  a 2.x version of the Serverless framework to be installed
  but this was not compatible with the newer versions of the
  warmup plugin thus the TypeError mentioned above
* All impacted dependencies have been updated and pinned via
  `package-lock.json` as well as `frameworkVersion` field in
  the `serverless.yml`